name: Deploy Laravel to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 217.154.102.150
          username: ferter.es_9vlc3g5trec
          key: ${{ secrets.DEPLOY_KEY }}
          key_format: "base64"
          script: |
            cd /var/www/vhosts/ferter.es/ioc.ferter.es
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:clear
            echo "✅ Deploy completado correctamente"
